### ISSUE TITLE
Find a new locations database with population

### ISSUE THREAD

**Issue by mariuszmalek** [LeadBrowser/leads-generator-app#23]
**Is your feature request related to a problem? Please describe.**
Now we can't use with condition -> population. This function helps us sort the cities we are actually searching.

**Describe the solution you'd like**
When we have a new database with all the countries of the world, countries and cities that have populations, then we can use this function to search condition.

**Comment by Pavan-Nambi** [comment]
hey can you elaborate a bit if you dont mind?

**Comment by mariuszmalek** [comment]
@Pavan-Nambi , one of the most important function for search prospects (contacts data) based on location need a database with locations in all around the world (countries, states, cities). 

Now our data base dosen't have information on population in each cities. This is a reason why we can't use of this condition

<img width="1129" alt="Zrzut ekranu 2023-01-2 o 12 19 37" src="https://user-images.githubusercontent.com/26696860/210224482-e5e90355-6033-41f2-bee2-b4abb69bc41a.png">

**Comment by Pavan-Nambi** [comment]
so we need some dataset like https://www.kaggle.com/datasets/juanmah/world-cities ?? to fill database?

**Comment by mariuszmalek** [comment]
You just fixed the problem <3
